name = "GrowthParameterEstimationGUI"
uuid = "3fa4ee3a-3ac0-4e53-9d87-70e29f87a34b"
authors = ["GrowthParameterEstimation contributors"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GrowthParameterEstimation = "f2d48b76-d258-4732-aa20-f5a609aab424"
GenieFramework = "a59fdf5c-6bf0-4f5d-949c-a137c9e2f353"
StippleUI = "a3c5d34a-b254-4859-a8fa-b86abb7e84a3"
StipplePlotly = "ec984513-233d-481d-95b0-a3b58b97af2b"

[compat]
julia = "1.10"
CSV = "0.10"
DataFrames = "1"
GrowthParameterEstimation = "0.3"
GenieFramework = "3"
StippleUI = "0.24"
StipplePlotly = "0.14"
